# Python Tutorial

**Heading**
<br>
*Italic heading*

# Title
## Subheading
### Sub sub heading
#### smaller suvbheading
##### italic subheading

`Himanshi is good.`
>HIMANSHI
>>JAIN

- HIMANSHI

1.himanshi

<font color= red> 
HIMANSHI </font>

$himanshi$

In [ ]:
print("This is my first line of code")


In [ ]:
print("Himanshi\n This is my first line of code")

In [ ]:
a=6
b=7
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
#remainder
print (a%b)
#exponential
print(a**b)

In [ ]:
print(4*5-9+6/7)

In [ ]:
a=9
a=a+1
print(a)
a=a-1
print(a)

In [ ]:
print(3>4)
print(True and False)
print(True or False)
print(a!=b)
print(True and not False)

In [ ]:
s="   himanshi jain k  "
print(s.rstrip())
inc='4%'
print(inc.rstrip("%"))
print(s.lstrip())
print(s.strip())

In [ ]:
##indexing and slicing
val="2 apples"
no=val[0]
print("number of apple is",no)

what=val[2:]
print(what)
print(val[2:5])
print(val[3:5])
print(val[:6])

num="123456789"
print(num[1::2])
print(num[0::2])

A="Data"
B="Analysis"
C="Panda"

print("{0} {1} using {2}".format(A,B,C))

In [ ]:
input = 'Kumar_Ravi_003'
print(input[6:10])
print(input[0:5])
print(input[11:15])

In [ ]:
#list
initial_list=[]
print(initial_list)
initial_list=[2,'h',"jain"]
print(initial_list)
print(initial_list[0])
print(initial_list[1:3])
print(initial_list[0:2])
print(initial_list[-1])
print(initial_list[-2])
print(initial_list[:-2])

#initial_list.pop(0)
print(initial_list.pop(0))
initial_list.append('R')
print(initial_list)
#Remove SPSS from input_list=['SAS', 'R', 'PYTHON', 'SPSS'] and add 'SPARK' in its place.
input_list=['SAS', 'R', 'PYTHON', 'SPSS']
input_list.pop()
print(input_list)
input_list.append('SPARK')
print(input_list)

#String to list
sentence="himanshi is a. good. girl"
words=sentence.split()
print(words)
words1=sentence.split('.')
print(words1)

#list to string
L1=['Himanshi','Jain']
list=''.join(L1)
print(list)
list=' '.join(L1)
print(list)

#convert a string input_str = 'I love Data Science & Python' to a list by splitting it on ‘&’.
input_str = 'I love Data Science & Python'
list1=input_str.split('&')
print(list1)

#extra features
my_list=["hi"]
print(my_list*5)
print(my_list+my_list)
print(len(my_list))

list2=['2','4','1']
print(sorted(list2))
print(max(list2))
print(min(list2))

#nested list
list3=[[1,2,3],[4,5,6,7],[1]]
print(list3[0])
print(list3[0:2])

#Convert a list ['Pythons syntax is easy to learn', 'Pythons syntax is very clear'] to a string using ‘&’. 
list4=['Pythons syntax is easy to learn', 'Pythons syntax is very clear'] 
str=' & '.join(list4)
print(str)

#Extract Python from a nested list input_list =  [['SAS','R'],['Tableau','SQL'],['Python','Java']]
input_list =  [['SAS','R'],['Tableau','SQL'],['Python','Java']]
print(input_list[2][0])


In [ ]:
#Tuples
tuple1=('a',1,'himanshi')
print(tuple1[0])
#tuple to list
c=list(tuple1)
print(c)


In [ ]:
#Dictionaries

dict1={'Name':"hima",'Age':21}
print(dict1)
ValueExtract=dict1['Name']
print(ValueExtract)

value=dict1.get('Name')
print(value)
value1=dict1.get('Height')
print(value1)

#From a Dictionary input_dict={'Name': 'Monty', 'Profession': 'Singer' },
#get the value of a key ‘Label’ which is not a part of the dictionary, in such a way that Python doesn't hit an error.
#If the key does not exist in the dictionary, Python should return 'NA'.
input_dict={'Name': 'Monty', 'Profession': 'Singer'}
print(input_dict.get('Label','NA'))

#replacing value
dict1['Age']=25
print(dict1)

#adding key-value to dict
dict1['height']=55.1
print(dict1)


#if key already present
print('Age' in dict1)

#get list of all keys
print(list(dict1.keys()))
#get list of all values
print(list(dict1.values()))

#assign more than 1 values:
new_dict=dict(Name=['Hima','Jain'],Age=5)
print(new_dict)

#concatenation of two dict
dict1.update(new_dict)
print(dict1)

#deleteing key
del dict1['Name']
print(dict1)

#length of dict
print(len(dict1))

#Extract the company headed by Tim Cook from the dictionary 
dict2={'Jack Dorsey': 'Twitter', 'Tim Cook': 'Apple','Jeff Bezos': 'Amazon','Mukesh Ambani': 'RJIO'}
value=dict2.get('Tim Cook')
print(value)

#Create a SORTED list of all values from the dictionary 
input_dict = {'Jack Dorsey' : 'Twitter' , 'Tim Cook' : 'Apple','Jeff Bezos' : 'Amazon' ,'Mukesh Ambani' : 'RJIO'}
print(list(input_dict.values()))


In [ ]:
#sets

std_list1=['a','a','b','c','c','e','n','1']
std_set1=set(std_list1)
print(std_set1)

#find oput class
print(type(std_set1))

#set operations
std_list2=['1','2','3','1','2','a']
std_set2=set(std_list2)
print(std_set2)

print(std_set1.union(std_set2))
print(std_set1.intersection(std_set2))
print(std_set1.difference(std_set2))

In [ ]:
#Control structures

#conditional statement:
score=int(input("enter score"))
passing=40
dist=90

if score>=dist:
    print("top")
elif score==passing:
    print("passed")
elif score==passing<dist:
     print("yes")
else :
    print("fail")
    
#looping constructs:
for i in range(1,4):
    print(i)
    if(i>=3):
        #break
        #pass
        continue
        print("hello")

start=3
while start<5:
    print("hey")
    start=start+1
    
d = {0: 'Fish', 1: 'Bird', 2: 'Mammal'}
for i in d:
    print(i)
    


In [ ]:
#list comprehensions:
#example 1
s_list=[]
for x in range(1,4):
    s_list.append(x**2)
print(s_list)
#OR YOU CAN USE LIST COMPREHENSION
s_list=[x**2 for x in range(1,4)]
print(s_list)

#example2
single_list=[ ]
para=["this is", "himanshi jain" ]
for sentence in para:
    for word in sentence.split( ):
        single_list.append(word)
print(single_list)
#this can be written as in string comprehension.
single_list=[word for sentence in para for word in sentence.split()]
print(single_list)

#You are given an integer 'n' as the input. Create a list 
#comprehension containing the squares of the integers from 1 till n^2 (including 1 and n), and print the list. 

n=int(input("enter n "))
input_list=[n**2 for n in range(1,n)]
print(input_list)

#Extract the words that start with a vowel from a list 
input_list=['wood', 'old', 'apple', 'big', 'item', 'euphoria']
new_list=[word for word in input_list if word[0] in 'aeiou']
print(new_list)


In [ ]:
##Functions:
def scream():
    print('hello')
scream()

num=int(input("num is"))

def square(num):
    out=num**2
    print("square is "+ str(out))
square(num)

#Create a function squared(),
#which takes x and y as arguments and returns the x**y value. For e.g., if x = 2  and y = 3 , then the output is 8.
def squared(x,y):
    out=x**y
    return out
print(squared(2,3))

#create factorial program
def factorial(num):
    if num<=1:
        return 1
    else:
        fact=num*factorial(num-1)
        return fact
print(factorial(3))

#take more than one argument.
def addition(*args):
    print(args)
    return(sum(args))
addition(1,2,3,4,5)

#string as argument:
def proper(some):
    #some=some.strip()
    some=" ".join([word[0].upper() + word[1:] for word in some.split()])
    print(some)
    some=" ".join([word[0].upper() for word in some.split()])
    return some
captain=proper("himanshi jain")
print(captain)

#string as argument:
def hey(text):
    text=text.split()
    print(text)
hey("Himanshi mithil verma")

#Lambda function:
join_by_comma = lambda x,y:x*y
print(join_by_comma(3,4))

#example:
string_to_list=lambda x:x.split()
print(string_to_list("Himanshi Jain"))
print(type(string_to_list))

#Create a lambda function 'greater', which takes two arguments x and y and return x if x>y otherwise y.
#If x = 2 and y= 3, then the output should be 3.
greater= lambda x,y:x if x>y else y
print(greater(3,4))



In [ ]:
#Map:
f_list=[2,3,4]
print(map(lambda x:x**2,f_list))
print(list(map(lambda x:x**2,f_list)))

#Using the Map function, create a list 'cube', which consists of the cube of numbers in input_list.
#if the input list is [5,6,4,8,9], the output should be [125, 216, 64, 512, 729].
input_list=[5,6,4,8,9]
print(list(map(lambda x:x**3,input_list)))

#Using the function Map, count the number of words that start with ‘S’ in input_list.
input_list2 = ["Sa","Si","Ho"]
print(list(map(lambda x:x[0]=='S',input_list2)))

#example using two input args
list1=[1,2]
list2=[3,4]
print(list(map(lambda x,y:x+y,list1,list2)))

#Filter:
#Filter' is a similar operation, but it requires the function to look for a condition and then, only returns
#those elements from the collection that satisfy the condition.
list3=[1,2,3,6]
print(list(filter(lambda x:x%3==0,list3)))

#Create a list ‘name’ consisting of the combination of the first name and the second name from list 1 and 2 respectively. 
list4=['Himanshi','mithil']
list5=['jain','verma']
name=list(map(lambda x,y:x[0:]+' '+y[0:],list4,list5))
print(name)

#Reduce 
from functools import reduce
print(reduce(lambda x,y:x+y,range(1,4))) #0,1,2,3

list5=[1,2,3,4,5]
print(reduce(lambda x,y:x if x<y else y,list5))

#Extract a list of numbers that are multiples of 5 from a list of integers named input_list.
input_list1=[5,2,10,1]
print(list(filter(lambda x:x%5==0,input_list1)))

#You are given a list of strings such as input_list =  ['hdjk', 'salsap', 'sherpa'].
#Extract a list of names that start with an ‘s’ and end with a ‘p’ (both 's' and 'p' are lowercase) in input_list.
input_list =['hdjk','salsap','sherpa']
print(list(filter(lambda x:x[0]=='s'and x[-1]=='p',input_list)))

#Using the Reduce function, concatenate a list of words in input_list, and print the output as a string.
#If input_list = ['I','Love','Python'], the output should be the string 'I Love Python'.
input_list4 = ['I','Love','Python']
print(reduce(lambda x,y:x+" "+y,input_list4))


In [23]:
#Numpy::
#Check whether Numpy is installed:
try:
    import numpy 
    print("yes")
except ImportError:
    print ("numpy is not installed")
    #If yes,then which version:
print(numpy.__version__)

#numpy basics:
import numpy as np
arr=np.array([1,2,3])
print(arr)

#Create a 3*3 array using list_1 = [1,2,3] list_2 = [4,5,6] list_3 = [7,8,9]
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

#why array is better than list::
list1=[1,2]
list2=[3,4]
#list way to do it:
prod=list(map(lambda x,y:x*y,list1,list2))
print(prod)
#array way to do it:
arr3=np.array([list1])
arr4=np.array([list2])
arr5=arr3*arr4
print(arr5)
print(type(arr5))

#Perform an element-wise multiplication using list_1 = [2,3,4,5] list_2 = [7,8,9,6] and obtain the output as a list. 
arr6=np.array([2,3,4,5])
arr7=np.array([7,8,9,6])
print(list(arr6*arr7))
print(type(list(arr6*arr7)))

yes
1.16.5
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3, 8]
[[3 8]]
<class 'numpy.ndarray'>
[14, 24, 36, 30]
<class 'list'>
